INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (1, null, 'Bonsai', 'Categoría padre para tipos de bonsai');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (2, 1, 'Moyogi', 'Es el estilo más común de bonsái, caracterizado por un tronco recto y una corona simétrica.');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (3, 1, 'Fukinagashi', e'Se refiere a un bonsái con ramas que se inclinan en una dirección, como si estuvieran siendo sopladas por el viento.
');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (4, 1, 'Kabudachi', 'Es un estilo de bonsái que se cultiva con varios troncos, lo que le da una apariencia de bosque.');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (5, 1, 'Literati', 'Este estilo de bonsái se caracteriza por un tronco retorcido y ramas curvas.');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (6, 1, 'Shakan', 'Se trata de un estilo de bonsái en el que el tronco se inclina en un ángulo agudo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (7, 1, 'Ikadabuki', 'Es un estilo de bonsái que presenta una sola rama que se extiende hacia arriba como un dedo índice.');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (8, 1, 'Han-Kengai', 'Este estilo de bonsái se caracteriza por el tronco inclinado hacia abajo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (9, 1, 'Yose-ue', 'Es un estilo de bonsái que involucra varios árboles plantados juntos en un solo recipiente para crear un efecto de bosque.');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (10, 1, 'Neagari', 'Es un estilo de bonsái en el que el tronco está completamente expuesto en la superficie del suelo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (11, 1, 'Ishitsuki', 'Se refiere a un estilo de bonsái en el que el árbol se cultiva en una roca');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (12, null, 'Sustrato', 'Sustrato para bonsai');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (13, null, 'Herramientas', 'Herramientas para bonsai');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (14, null, 'Macetas', 'Macetas para bonsai');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (15, 12, 'Akadama', 'Un sustrato japonés hecho de arcilla volcánica');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (16, 12, 'Kiryuzuna', 'También conocido como arena de río');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (17, 12, 'Kanuma', 'Es otro sustrato japonés que se utiliza comúnmente para bonsáis de coníferas. Está hecho de tierra volcánica ácida y es especialmente bueno para las plantas que requieren un pH bajo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (18, 12, 'Sphagnum moss', 'Es un tipo de musgo que se utiliza a menudo como sustrato para bonsáis. Tiene una capacidad de retención de agua muy alta y ayuda a mantener las raíces húmedas');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (19, 12, 'Tierra para macetas', 'es un sustrato común que se puede utilizar para bonsáis. Es una mezcla de tierra');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (20, 12, 'Piedra pómez', 'Es un sustrato ligero que se utiliza para mejorar el drenaje en la base del bonsái. También puede ayudar a reducir la compactación del sustrato y mejorar la aireación de las raíces');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (21, 12, 'Perlita', 'Es un sustrato de origen volcánico muy ligero que se utiliza a menudo en mezclas de sustratos para bonsáis. Tiene una capacidad de retención de agua moderada y ayuda a mejorar la aireación del sustrato');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (22, 12, 'Vermiculita', 'Es un sustrato similar a la perlita');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (23, 13, 'Tijeras de podar', 'Se utilizan para cortar ramas y hojas de un bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (24, 13, 'Cizallas de hoja larga', 'se utilizan para podar ramas más gruesas en un bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (25, 13, 'Cizallas de yunque', 'se utilizan para cortar ramas y hojas de un bonsái con menos esfuerzo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (26, 13, 'Tijeras de defoliación', 'se utilizan para eliminar las hojas de un bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (27, 13, 'Pinzas de agarrar', 'se utilizan para trabajar en ramas pequeñas y ajustar el alambre');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (28, 13, 'Gancho de raíz', 'se utilizan para limpiar la tierra de las raíces del bonsái y ajustar el alambre');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (29, 13, 'Cepillo de raíz', 'se utilizan para limpiar la tierra de las raíces del bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (30, 13, 'Cincel de raíz', 'se utilizan para separar y cortar las raíces del bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (31, 13, 'Sierra', 'se utilizan para cortar ramas gruesas de un bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (32, 13, 'Alicate', 'se utilizan para ajustar y cortar el alambre que se usa para dar forma a un bonsái');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (33, 14, 'Macetas de cerámica', 'son las macetas más comunes para los bonsáis. Están disponibles en varios tamaños');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (34, 14, 'Macetas de madera', 'son una opción más rústica para los bonsáis. Están disponibles en diferentes tipos de madera');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (35, 14, 'Macetas de arcilla', 'son macetas porosas que permiten una mejor circulación del aire y el agua. Sin embargo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (36, 14, 'Macetas de plástico', 'son una opción económica para los bonsáis. Son resistentes');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (37, 14, 'Macetas de vidrio', 'son una opción menos común para los bonsáis. Permiten una visión completa de las raíces y pueden ser interesantes desde el punto de vista decorativo');
INSERT INTO public.categoría (categoria_id, categoria_padre, nombre, descripcion) VALUES (38, 14, 'Macetas de metal', 'son una opción más moderna para los bonsáis. Están disponibles en diferentes acabados y pueden ser duraderas y resistentes a la intemperie. Sin embargo');
